openapi: 3.1.0
info:
  title: Standard API
  version: '1.0'
  summary: The Client Service Standard API is a client agnostic API to the client servvice.
  description: The Client Service Standard API is a client agnostic API to the client servvice.
servers:
  - url: 'http://localhost:3000'
tags:
  - name: Branding
  - name: Customers
  - name: Users
  - name: Business data synchronization
  - name: System
paths:
  /customers:
    get:
      summary: Get customers
      tags:
        - Customers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/customer'
      operationId: get-customers
      description: Gets a collection of customers
      parameters:
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/offset'
        - schema:
            type: boolean
            default: false
          in: query
          name: includeDeleted
          description: 'Filters customers based on user status. If true only customers with status ''deleted'' will pass the filter, if false only customers with a status not equal to ''deleted'' will pass the filter.'
        - schema:
            type: boolean
            default: true
          in: query
          name: includeDeactivated
          description: 'Filters customers based on user status. If true only customers with status ''deactivated'' will pass the filter, if false only customers with a status not equal to ''deleted'' status will pass the filter.'
        - schema:
            type: boolean
          in: query
          name: includeActive
          description: 'Filters customers based on user status. If true only customers with status ''active'' will pass the filter, if false only customers with a status not equal to ''active'' will pass the filter.'
        - schema:
            type: string
          in: query
          name: customerId
          description: Filters for customers based on the customerId. Note that the customer Id is only unique within all customers of the same reseller.
        - schema:
            type: string
            format: uuid
          in: query
          name: resellerId
          description: Filters for sub customer of the given reseller.
      x-internal: true
  '/customers/{id}/assigned-customer-branding':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: '/customers/{id}/assigned-customer-branding'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/customerBranding'
      operationId: get-customers-id-roles
      description: Gets the assigned customer branding for this specific customer
      parameters: []
      x-internal: true
      tags:
        - Customers
    put:
      summary: '/customers/{id}/assigned-customer-branding'
      operationId: put-customers-id-assigned-customer-branding
      responses:
        '200':
          description: OK
      description: Creates or updates the customer branding
      tags:
        - Customers
  '/customers/{id}/assigned-customer-roles':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: ''
      tags:
        - Customers
      responses: {}
      operationId: get-customers-id-roles
      description: Gets assigned roles to this customer
      parameters:
        - schema:
            type: string
            format: uuid
          in: query
          name: userId
          description: If given filters the list for roles assigned to that specific user
        - schema:
            type: integer
            minimum: 1
            default: 100
            maximum: 1000
          in: query
          name: limit
          description: 'Pagination, maximum page size'
        - schema:
            type: integer
            minimum: 0
          in: query
          name: offset
          description: 'Pagination, page offset'
        - schema:
            type: string
          in: query
          name: assignedAfter
          description: Filters for roles assigned after the given date
      x-internal: true
    post:
      summary: ''
      operationId: post-customers-id-roles
      responses:
        '200':
          description: OK
      description: Assignes a new role for a suser on this customer
      tags:
        - Customers
  '/customers/{id}/effective-branding':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: '/customers/{id}/effective-branding'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/branding'
      operationId: get-customers-id-roles
      description: Gets the effecive branding for this customer.
      parameters: []
      x-internal: true
      tags:
        - Customers
  '/customers/{id}/efective-customer-roles':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: Id of the customer
    get:
      summary: ''
      tags:
        - Customers
      responses: {}
      operationId: get-customers-id-roles
      description: Gets effective roles applied to this customer.
      parameters:
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/offset'
        - schema:
            type: string
            format: uuid
          in: query
          name: userId
          description: Filters the collection for the given user id
      x-internal: true
  '/customers/{id}/sub-customers':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Get sub-customers of a customer
      tags:
        - Customers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/customerLight'
      operationId: get-customers-id-reseller-relations
      x-internal: false
      description: Gets all the sub-customers of a customer
      parameters:
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/offset'
  '/customers/{id}/reseller-relations/{relation-id}/customer-roles':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
      - schema:
          type: string
        name: relation-id
        in: path
        required: true
    get:
      summary: ''
      responses:
        '200':
          description: OK
      operationId: get-customers-reseller-relations-roles
      description: 'Gets all customer roles assigned to this relation, i.e. if a customer role is assigned to a cutomer relation that role is assigned to the customer that is child of the releati automatically.'
      x-internal: true
      tags:
        - Customers
    delete:
      summary: ''
      operationId: delete-customers-id-reseller-relations-relation-id
      responses:
        '200':
          description: OK
      description: Deletes this relation
      tags:
        - Customers
  /system/roles:
    get:
      summary: ''
      responses: {}
      operationId: get-roles
      description: Gets a list of roles defined for the system.
      parameters:
        - schema:
            type: string
          in: query
          name: limit
        - schema:
            type: string
          in: query
          name: offset
        - schema:
            type: string
          in: query
          name: user
      x-internal: true
      tags:
        - System
    parameters: []
  /synchronization/customers:
    parameters: []
    get:
      summary: Get customers for synchronization
      operationId: get-synchronization-customers
      responses:
        '200':
          description: OK
          headers:
            X-Total-Count:
              schema:
                type: integer
              description: Total count of resources in the collection.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/customer'
              examples:
                example-1:
                  value:
                    - id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                      firstName: John
                      lastName: Doe
                      emailAddress: john@doe.com
                      preferredCulture: de-AT
                      mobilePhoneNumber: +43 664 9161413
                      gender: diverse
                      createdAt: '2021-08-23T16:15:18.123+01:00'
                      latestUpdateAt: '2021-08-23T16:15:18.123+01:00'
                      synchronizationId: 0e45b7ef-0a0a-4d71-b486-8536460bb9b7
                      synchronizationInformation: string
                      status: string
                      '': string
        '401':
          description: Unauthorized
      description: Gets customer with detail information useful for synchronization with other systems.
      parameters:
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/offset'
        - schema:
            type: boolean
            default: false
          in: query
          name: includeDeleted
          description: 'Filters customers based on user status. If true only customers with status ''deleted'' will pass the filter, if false only customers with a status not equal to ''deleted'' will pass the filter.'
        - schema:
            type: boolean
            default: true
          in: query
          name: includeDeactivated
          description: 'Filters customers based on user status. If true only customers with status ''deactivated'' will pass the filter, if false only customers with a status not equal to ''deleted'' status will pass the filter.'
        - schema:
            type: boolean
          in: query
          name: includeActive
          description: 'Filters customers based on user status. If true only customers with status ''active'' will pass the filter, if false only customers with a status not equal to ''active'' will pass the filter.'
        - schema:
            type: string
            format: uuid
            example: 98aea202-354b-4912-81f7-364e609fe650
          in: query
          name: synchronizationId
          description: Filters for a customer with the given synchronization Id. Only a customer with an exact match will pass the filter.
        - schema:
            type: string
            example: '2021-11-12T21:15:13.1234+01:00'
          in: query
          name: latestUpdatedAfter
          description: Filters for customers  that were last updated in the system after (>) the given date.
        - schema:
            type: string
            example: '2021-11-12T21:15:13.1234+01:00'
          in: query
          name: createdBefore
          description: 'Filters for customers  that were created in the system before (<) the given date. '
        - schema:
            type: boolean
          in: query
          name: synchronizationIdAvailable
          description: 'Filters for customers based on the availability of a synchronizationId. If set to true only users with a non-empty synchronizationId will pass the filter, if set to false only users with an empty synchronizationId will pass the filter.  '
        - schema:
            type: string
          in: query
          name: customerNumber
          description: Filters for customers based on the customer number. Note that the customer Id is only unique within all customers of the same reseller.
        - schema:
            type: string
            format: uuid
          in: query
          name: resellerId
          description: Filters for sub customer of the given reseller.
      tags:
        - Business data synchronization
        - Users
    put:
      summary: ''
      operationId: put-synchronization-users
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
      description: 'Creates a new user and '
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/synchronization-user'
      tags:
        - Business data synchronization
  '/synchronization/customers/{id}':
    parameters:
      - schema:
          type: string
          format: uuid
        name: id
        in: path
        required: true
        description: Id of the customer
    get:
      summary: Get customers for synchronization
      operationId: get-synchronization-customers
      responses:
        '200':
          description: OK
          headers:
            X-Total-Count:
              schema:
                type: integer
              description: Total count of resources in the collection.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/customer'
              examples:
                example-1:
                  value:
                    - id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                      firstName: John
                      lastName: Doe
                      emailAddress: john@doe.com
                      preferredCulture: de-AT
                      mobilePhoneNumber: +43 664 9161413
                      gender: diverse
                      createdAt: '2021-08-23T16:15:18.123+01:00'
                      latestUpdateAt: '2021-08-23T16:15:18.123+01:00'
                      synchronizationId: 0e45b7ef-0a0a-4d71-b486-8536460bb9b7
                      synchronizationInformation: string
                      status: string
                      '': string
        '401':
          description: Unauthorized
      description: Gets customer with detail information useful for synchronization with other systems.
      parameters: []
      tags:
        - Business data synchronization
        - Users
    put:
      summary: ''
      operationId: put-synchronization-users
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
      description: 'Creates a new user and '
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/synchronization-user'
      tags:
        - Business data synchronization
  '/synchronization/customers/{id}/reseller-relations':
    parameters:
      - schema:
          type: string
          format: uuid
        name: id
        in: path
        required: true
        description: Id of the customer
    get:
      summary: Get customer's reseller relations
      operationId: get-synchronization-customers
      description: Gets all reseller relations of this customer i.e. all relations between customers where this customer is the reseller.
      parameters:
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/offset'
      tags:
        - Business data synchronization
        - Users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/customerRelation'
    post:
      summary: ''
      operationId: post-synchronization-customers-id-reseller-relations
      responses:
        '200':
          description: OK
  '/synchronization/customers/{id}/reseller-relations/{relation-id}':
    parameters:
      - schema:
          type: string
          format: uuid
        name: id
        in: path
        required: true
        description: Id of the customer
      - schema:
          type: string
        name: relation-id
        in: path
        required: true
        description: Id of the reseller relation
    get:
      summary: Get customer's reseller relations
      operationId: get-synchronization-customers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/customerRelation'
      description: Gets all reseller relations of this customer i.e. all relations between customers where this customer is the reseller.
      parameters: []
      tags:
        - Business data synchronization
        - Users
    delete:
      summary: ''
      operationId: delete-synchronization-customers-id-reseller-relations-relation-id
      responses:
        '200':
          description: OK
  /synchronization/users:
    parameters: []
    get:
      summary: Get users for synchronization
      operationId: get-synchronization-users
      responses:
        '200':
          description: OK
          headers:
            X-Total-Count:
              schema:
                type: integer
              description: Total count of resources in the collection.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/synchronizationUser'
              examples:
                example-1:
                  value:
                    - id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                      firstName: John
                      lastName: Doe
                      emailAddress: john@doe.com
                      preferredCulture: de-AT
                      mobilePhoneNumber: +43 664 9161413
                      gender: diverse
                      createdAt: '2021-08-23T16:15:18.123+01:00'
                      latestUpdateAt: '2021-08-23T16:15:18.123+01:00'
                      synchronizationId: 0e45b7ef-0a0a-4d71-b486-8536460bb9b7
                      synchronizationInformation: string
                      status: string
                      '': string
        '401':
          description: Unauthorized
      description: Gets registered users with detail information useful for synchronization with other systems.
      parameters:
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/offset'
        - schema:
            type: boolean
            default: false
          in: query
          name: includeDeleted
          description: 'Filters users based on user status. If true only users with status ''deleted'' will pass the filter, if false only users with a status not equal to ''deleted'' will pass the filter.'
        - schema:
            type: boolean
            default: true
          in: query
          name: includeDeactivated
          description: 'Filters users based on user status. If true only users with status ''deactivated'' will pass the filter, if false only users with a status not equal to ''deleted'' status will pass the filter.'
        - schema:
            type: boolean
          in: query
          name: includeActive
          description: 'Filters users based on user status. If true only uses with status ''active'' will pass the filter, if false only users with a status not equal to ''active'' will pass the filter.'
        - schema:
            type: string
            format: email
            example: jon@doe.com
          in: query
          name: emailAddress
          description: Filter for user with the given e-mail address. The match is case insensitive.
        - schema:
            type: string
            format: uuid
            example: 98aea202-354b-4912-81f7-364e609fe650
          in: query
          name: synchronizationId
          description: Filters for a user with the given synchronization Id. Only a user with an exact match will pass the filter.
        - schema:
            type: string
            example: '2021-11-12T21:15:13.1234+01:00'
          in: query
          name: lastUpdatedAfter
          description: Filters for users that were last updated in the system after (>) the given date.
        - schema:
            type: string
            example: '2021-11-12T21:15:13.1234+01:00'
          in: query
          name: createdBefore
          description: 'Filters for users that were created in the system before (<) the given date. '
        - schema:
            type: boolean
          in: query
          name: synchronizationIdAvailable
          description: 'Filters for users based on the availability of a synchronizationId. If set to true only users with a non-empty synchronizationId will pass the filter, if set to false only users with an empty synchronizationId will pass the filter.  '
      tags:
        - Business data synchronization
        - Users
    put:
      summary: ''
      operationId: put-synchronization-users
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
      description: 'Creates a new user and '
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/synchronization-user'
      tags:
        - Business data synchronization
  '/synchronization/users/{id}':
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
        description: UUID of the collection element
    get:
      summary: Get specific user for synchronization
      operationId: get-synchronoization-users-Id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/synchronization-user'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '404':
          description: Not Found
      description: Gets a specific user with detail information useful for synchronization with other systems.
      tags:
        - Business data synchronization
    put:
      summary: Update specific user with synchronization details
      operationId: put-users-id
      responses:
        '200':
          description: OK
      description: Updates a suer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/synchronization-user'
      tags:
        - Business data synchronization
    patch:
      summary: Patch a specific user
      operationId: patchsynchronization-users-uuid
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/synchronization-user'
      tags:
        - Business data synchronization
  /system/instance-branding:
    get:
      summary: Get instance branding
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/branding'
        '':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/branding'
      operationId: get-instance-branding
      description: Gets the whole definietion of the instance branding.
      tags:
        - System
    put:
      summary: Put instance branding
      operationId: put-system-branding
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/branding'
      description: Sets the branding for the whole instance
      tags:
        - System
    parameters: []
  '/synchronization/users/{id}/synchronization-information':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Get synchronization information for specific user
      operationId: get-synchronization-user-synchronization-information
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
      description: Gets the synchronization information of a specific user.
      tags:
        - Business data synchronization
    put:
      summary: Update synchronization information for specific user
      operationId: put-users-id-synchronization-information
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '404':
          description: Not Found
      description: Updates a suer
      requestBody:
        content:
          application/json:
            schema:
              type: string
              description: A JSON document with information important for the synchronization process. The schema of the JSON is defined by the synchronization process.
      tags:
        - Business data synchronization
  /users:
    parameters: []
    get:
      summary: Users
      operationId: get-users
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
      description: Gets registered users.
      parameters:
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/offset'
        - schema:
            type: integer
          in: header
          name: X-Total-Count
          description: Total number of elements in the collection.
        - schema:
            type: boolean
          in: query
          name: includeDeleted
          description: Include or exclude uses with status 'deleted'.
        - schema:
            type: boolean
          in: query
          name: includeDeactivated
          description: Include or exclude uses with status 'deactivated'.
        - schema:
            type: boolean
          in: query
          name: includeActive
          description: Include or exclude uses with status 'active'.
      tags:
        - Users
    post:
      summary: ''
      operationId: post-users
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
      tags:
        - Users
  '/users/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Get user by Id
      operationId: get-users-uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
      description: Gets a specific user.
      tags:
        - Users
    put:
      summary: Put user
      operationId: put-users-id
      responses:
        '200':
          description: OK
      description: Updates a specific user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
      tags:
        - Users
  '/users/{id}/status':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Get user status
      operationId: get-users-Id-status
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userStatus'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      description: Gets a the status of a specific user
      tags:
        - Business data synchronization
    put:
      summary: Update user status
      operationId: put-user-status
      description: Updates a user's status
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userStatus'
        description: ''
      tags:
        - Business data synchronization
      responses:
        '200':
          description: OK
        '406':
          description: 'Not Acceptable. The requested user status change is not acceptable. '
  '/users/{id}/mask':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    put:
      summary: Mask a user
      operationId: put-users-id-mask
      responses:
        '200':
          description: OK
      description: 'Will remove all personal information of a user, thus removing the relation to a natural person.'
      tags:
        - Users
  '/users/{id}/assigned-system-roles':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: ID of  the user in the HsM system.
    get:
      summary: Get assigned system roles for user
      tags:
        - Users
      responses: {}
      operationId: get-users-id-systemroles
      description: Gets a list of systemroles assigned to that user.
      parameters:
        - schema:
            type: integer
          in: query
          name: limit
          description: 'Pagination, page size limit'
        - schema:
            type: integer
          in: query
          name: offset
          description: 'Pagination, page offset'
        - schema:
            type: string
          in: header
    post:
      summary: Add assigned system role for user
      operationId: post-users-id-systemroles
      responses:
        '200':
          description: OK
      description: Grant a system role to that user
      tags:
        - Users
    delete:
      summary: Delete an assigned system role of a user
      operationId: delete-users-id-assigned-system-roles
      responses:
        '200':
          description: OK
      tags:
        - Users
  '/users/{id}/assigned-customer-roles':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: ID of  the user in the HsM system.
    get:
      summary: Get assigned customer roles for user
      responses: {}
      operationId: get-users-id-customerroles
      description: Gets a list of effective roles the user has on the specified customer
      parameters:
        - schema:
            type: string
            format: uuid
          in: query
          name: customerId
      tags:
        - Users
    post:
      summary: Add a assigned customer role to a user
      operationId: post-users-id-assigned-customer-roles
      responses:
        '200':
          description: OK
      tags:
        - Users
components:
  schemas:
    branding:
      description: This model describes the branding of the instance or the effective branding for a customer
      type: object
      properties:
        productName:
          type: string
          minLength: 1
        displayModeDark:
          type: object
          properties:
            companyLogo:
              type: string
              minLength: 1
            navigationBarCompanyLogo:
              type: string
              minLength: 1
            mainColor300:
              type: object
              properties:
                hexCode:
                  type: string
                  minLength: 1
              required:
                - hexCode
            mainColor500:
              type: object
              properties:
                hexCode:
                  type: string
                  minLength: 1
              required:
                - hexCode
            mainColor700:
              type: object
              properties:
                hexCode:
                  type: string
                  minLength: 1
              required:
                - hexCode
            navigationBarColor:
              type: object
              properties:
                hexCode:
                  type: string
                  minLength: 1
              required:
                - hexCode
            navigationBarContrastColor:
              type: object
              properties:
                hexCode:
                  type: string
                  minLength: 1
              required:
                - hexCode
            selectionColor:
              type: object
              properties:
                hexCode:
                  type: string
                  minLength: 1
              required:
                - hexCode
          required:
            - companyLogo
            - navigationBarCompanyLogo
            - mainColor300
            - mainColor500
            - mainColor700
            - navigationBarColor
            - navigationBarContrastColor
            - selectionColor
        displayModeLight:
          type: object
          properties:
            companyLogo:
              type: string
              minLength: 1
            navigationBarCompanyLogo:
              type: string
              minLength: 1
            mainColor300:
              type: object
              properties:
                hexCode:
                  type: string
                  minLength: 1
              required:
                - hexCode
            mainColor500:
              type: object
              properties:
                hexCode:
                  type: string
                  minLength: 1
              required:
                - hexCode
            mainColor700:
              type: object
              properties:
                hexCode:
                  type: string
                  minLength: 1
              required:
                - hexCode
            navigationBarColor:
              type: object
              properties:
                hexCode:
                  type: string
                  minLength: 1
              required:
                - hexCode
            navigationBarContrastColor:
              type: object
              properties:
                hexCode:
                  type: string
                  minLength: 1
              required:
                - hexCode
            selectionColor:
              type: object
              properties:
                hexCode:
                  type: string
                  minLength: 1
              required:
                - hexCode
          required:
            - companyLogo
            - navigationBarCompanyLogo
            - mainColor300
            - mainColor500
            - mainColor700
            - navigationBarColor
            - navigationBarContrastColor
            - selectionColor
        instanceOperator:
          type: string
          minLength: 1
        clientSpecificOptions:
          type: object
          properties:
            webPortal:
              type: object
              properties:
                favIcon:
                  type: string
                  minLength: 1
              required:
                - favIcon
          required:
            - webPortal
      required:
        - productName
        - displayModeDark
        - displayModeLight
        - instanceOperator
        - clientSpecificOptions
      x-examples:
        example-1:
          productName: senseManagement
          displayModeDark:
            companyLogo: 'https://hagleitner.com/logos/hagleitnerLogo.dark.svg'
            navigationBarCompanyLogo: 'https://hagleitner.com/logos/hagleitnerLogo.dark.navigationbar.svg'
            mainColor300:
              hexCode: '#123456'
            mainColor500:
              hexCode: '#123456'
            mainColor700:
              hexCode: '#123456'
            navigationBarColor:
              hexCode: '#123456'
            navigationBarContrastColor:
              hexCode: '#123456'
            selectionColor:
              hexCode: '#123456'
          displayModeLight:
            companyLogo: 'https://hagleitner.com/logos/hagleitnerLogo.light.svg'
            navigationBarCompanyLogo: 'https://hagleitner.com/logos/hagleitnerLogo.light.navigationbar.svg'
            mainColor300:
              hexCode: '#123456'
            mainColor500:
              hexCode: '#123456'
            mainColor700:
              hexCode: '#123456'
            navigationBarColor:
              hexCode: '#123456'
            navigationBarContrastColor:
              hexCode: '#123456'
            selectionColor:
              hexCode: '#123456'
          instanceOperator: Hagleitner
          clientSpecificOptions:
            webPortal:
              favIcon: 'https://hagleitner.com/logos/hsm-favicon.svg'
    customer:
      type: object
      title: customer
      description: Describes a customer.
      properties:
        id:
          type: string
          format: uuid
          description: Id of the user within the HsM system.
          readOnly: true
        name:
          type: string
          example: John
          maxLength: 50
        address:
          type: string
          example: Doe
          maxLength: 50
        city:
          type: string
        postalCode:
          type: string
        countryCode:
          type: string
          description: ISO 3166-1 alpha-2 code
        emailAddress:
          type: string
          description: The users e-mail address. This address must be unique within all non deleted users in the HsM system.
          format: email
          example: john@doe.com
          maxLength: 256
        preferredCulture:
          type: string
          description: |-
            The culture the user wants to use in interaction with the system. Given as IETF BCP 47 language tag. If not given the system will use a default invariatn culture. 

            This cutlure is a default for this user, client systems might however choose to use another culture for interaction with the HsM system.
          example: de-AT
          maxLength: 35
        latestUpdatedAt:
          type: string
          description: 'Describes when the user was last modified within HsM. '
          format: date-time
          example: '2021-08-23T16:15:18.123+01:00'
          readOnly: true
        status:
          type: string
          enum:
            - active
            - inactive
            - deleted
          description: The status of the user in terms of his possibilty to interact with the system.
          readOnly: true
        isReseller:
          type: boolean
          description: Defines if a customer is a reseller. Customer marked as resellers can use HsM's reseller features.
        ResellerId:
          type: string
        InvoiceRecipientId:
          type: string
        ConditionProviderId:
          type: string
        ParentCompanyId:
          type: string
      required:
        - id
        - emailAddress
    customerLight:
      type: object
      title: customer
      description: Describes a customer.
      properties:
        id:
          type: string
          format: uuid
          description: Id of the user within the HsM system.
          readOnly: true
        name:
          type: string
          example: John
          maxLength: 50
        address:
          type: string
          example: Doe
          maxLength: 50
        city:
          type: string
        postalCode:
          type: string
        countryCode:
          type: string
          description: ISO 3166-1 alpha-2 code
      required:
        - id
    customerBranding:
      description: This model describes the branding for a customer
      type: object
      x-examples:
        example-1:
          productName: senseManagement
          displayModeDark:
            companyLogo: 'https://hagleitner.com/logos/hagleitnerLogo.dark.svg'
            navigationBarCompanyLogo: 'https://hagleitner.com/logos/hagleitnerLogo.dark.navigationbar.svg'
            mainColor300:
              hexCode: '#123456'
            mainColor500:
              hexCode: '#123456'
            mainColor700:
              hexCode: '#123456'
            navigationBarColor:
              hexCode: '#123456'
            navigationBarContrastColor:
              hexCode: '#123456'
            selectionColor:
              hexCode: '#123456'
          displayModeLight:
            companyLogo: 'https://hagleitner.com/logos/hagleitnerLogo.light.svg'
            navigationBarCompanyLogo: 'https://hagleitner.com/logos/hagleitnerLogo.light.navigationbar.svg'
            mainColor300:
              hexCode: '#123456'
            mainColor500:
              hexCode: '#123456'
            mainColor700:
              hexCode: '#123456'
            navigationBarColor:
              hexCode: '#123456'
            navigationBarContrastColor:
              hexCode: '#123456'
            selectionColor:
              hexCode: '#123456'
          instanceOperator: Hagleitner
          clientSpecificOptions:
            webPortal:
              favIcon: 'https://hagleitner.com/logos/hsm-favicon.svg'
      title: customerBranding
      properties:
        displayModeDark:
          type: object
          required:
            - companyLogo
            - navigationBarCompanyLogo
            - mainColor300
            - mainColor500
            - mainColor700
            - navigationBarColor
            - navigationBarContrastColor
            - selectionColor
          properties:
            companyLogo:
              type: string
              minLength: 1
            navigationBarCompanyLogo:
              type: string
              minLength: 1
            mainColor300:
              type: object
              required:
                - hexCode
              properties:
                hexCode:
                  type: string
                  minLength: 1
            mainColor500:
              type: object
              required:
                - hexCode
              properties:
                hexCode:
                  type: string
                  minLength: 1
            mainColor700:
              type: object
              required:
                - hexCode
              properties:
                hexCode:
                  type: string
                  minLength: 1
            navigationBarColor:
              type: object
              required:
                - hexCode
              properties:
                hexCode:
                  type: string
                  minLength: 1
            navigationBarContrastColor:
              type: object
              required:
                - hexCode
              properties:
                hexCode:
                  type: string
                  minLength: 1
            selectionColor:
              type: object
              required:
                - hexCode
              properties:
                hexCode:
                  type: string
                  minLength: 1
        displayModeLight:
          type: object
          required:
            - companyLogo
            - navigationBarCompanyLogo
            - mainColor300
            - mainColor500
            - mainColor700
            - navigationBarColor
            - navigationBarContrastColor
            - selectionColor
          properties:
            companyLogo:
              type: string
              minLength: 1
            navigationBarCompanyLogo:
              type: string
              minLength: 1
            mainColor300:
              type: object
              required:
                - hexCode
              properties:
                hexCode:
                  type: string
                  minLength: 1
            mainColor500:
              type: object
              required:
                - hexCode
              properties:
                hexCode:
                  type: string
                  minLength: 1
            mainColor700:
              type: object
              required:
                - hexCode
              properties:
                hexCode:
                  type: string
                  minLength: 1
            navigationBarColor:
              type: object
              required:
                - hexCode
              properties:
                hexCode:
                  type: string
                  minLength: 1
            navigationBarContrastColor:
              type: object
              required:
                - hexCode
              properties:
                hexCode:
                  type: string
                  minLength: 1
            selectionColor:
              type: object
              required:
                - hexCode
              properties:
                hexCode:
                  type: string
                  minLength: 1
      required:
        - displayModeDark
        - displayModeLight
    synchronizationCustomer:
      type: object
      title: synchronizationCustomer
      description: Describes a customer of the HsM system together with information relevant for synchronization with other business systems.
      properties:
        id:
          type: string
          format: uuid
          description: Id of the user within the HsM system.
          readOnly: true
        name:
          type: string
          example: John
          maxLength: 50
        address:
          type: string
          example: Doe
          maxLength: 50
        city:
          type: string
        postalCode:
          type: string
        countryCode:
          type: string
          description: ISO 3166-1 alpha-2 code
        emailAddress:
          type: string
          description: The users e-mail address. This address must be unique within all non deleted users in the HsM system.
          format: email
          example: john@doe.com
          maxLength: 256
        preferredCulture:
          type: string
          description: |-
            The culture the user wants to use in interaction with the system. Given as IETF BCP 47 language tag. If not given the system will use a default invariatn culture. 

            This cutlure is a default for this user, client systems might however choose to use another culture for interaction with the HsM system.
          example: de-AT
          maxLength: 35
        status:
          type: string
          enum:
            - active
            - inactive
            - deleted
          description: The status of the user in terms of his possibilty to interact with the system.
          readOnly: true
        latestUpdatedAt:
          type: string
          description: 'Describes when the user was last modified within HsM. '
          format: date-time
          example: '2021-08-23T16:15:18.123+01:00'
          readOnly: true
        createdAt:
          type: string
          format: date-time
          readOnly: true
        synchronizationId:
          type: string
          format: uuid
        synchronizationInformation:
          type: string
        isReseller:
          type:
            - string
            - boolean
          description: Defines if a customer is a reseller. Customer marked as resellers can use HsM's reseller features.
      required:
        - id
        - emailAddress
    synchronizationUser:
      type: object
      title: synchronizationUser
      description: Describes a user of the HsM system. Users are should generally be natural persons.
      properties:
        id:
          type: string
          format: uuid
          description: Id of the user within the HsM system.
          readOnly: true
        firstName:
          type: string
          example: John
          maxLength: 50
        lastName:
          type: string
          example: Doe
          maxLength: 50
        emailAddress:
          type: string
          description: The users e-mail address. This address must be unique within all non deleted users in the HsM system.
          format: email
          example: john@doe.com
          maxLength: 256
        preferredCulture:
          type: string
          description: |-
            The culture the user wants to use in interaction with the system. Given as IETF BCP 47 language tag. If not given the system will use a default invariatn culture. 

            This cutlure is a default for this user, client systems might however choose to use another culture for interaction with the HsM system.
          example: de-AT
          maxLength: 35
        mobilePhoneNumber:
          type: string
          description: 'Mobile phone number. This number will be used when the system wants to interact with that user via SMS, mobile phone numbers are not exposed to other users.'
          example: +43 664 9161413
        gender:
          type: string
          enum:
            - female
            - male
            - non-binary
          description: ''
        status:
          type: string
          enum:
            - active
            - inactive
            - deleted
          description: The status of the user in terms of his possibilty to interact with the system.
          readOnly: true
        createdAt:
          type: string
          format: date-time
          example: '2021-08-23T16:15:18.123+01:00'
          readOnly: true
        latestUpdatedAt:
          type: string
          description: 'Describes when the user was last modified within HsM. '
          format: date-time
          example: '2021-08-23T16:15:18.123+01:00'
          readOnly: true
        synchronizationId:
          type: string
          format: uuid
          description: Id of the user in an external system.
        synchronizationInformation:
          type: string
          description: A JSON document that can be used by synchronization processes to store synchronization information with this user. The schema of the JSON document is defined by the external synchronization process.
      required:
        - id
        - emailAddress
        - preferredCulture
        - createdAt
        - latestUpdatedAt
    user:
      type: object
      title: user
      description: Describes a user of the HsM system. Users in HsM will be linked to Azure B2C accounts by the unique e-mail address once a user first accesses HsM via B2C authentication.
      properties:
        id:
          type: string
          format: uuid
          description: Id of the user within the HsM system.
          readOnly: true
        firstName:
          type: string
          example: John
          maxLength: 50
        lastName:
          type: string
          example: Doe
          maxLength: 50
        emailAddress:
          type: string
          description: The users e-mail address. This address must be unique within all non deleted users in the HsM system.
          format: email
          example: john@doe.com
          maxLength: 256
        preferredCulture:
          type: string
          description: |-
            The culture the user wants to use in interaction with the system. Given as IETF BCP 47 language tag. If not given the system will use a default invariatn culture. 

            This cutlure is a default for this user, client systems might however choose to use another culture for interaction with the HsM system.
          example: de-AT
          maxLength: 35
        mobilePhoneNumber:
          type: string
          description: 'Mobile phone number. This number will be used when the system wants to interact with that user via SMS, mobile phone numbers are not exposed to other users.'
          example: +43 664 9161413
        gender:
          type: string
          enum:
            - female
            - male
            - non-binary
          description: ''
        latestUpdatedAt:
          type: string
          description: 'Describes when the user was last modified within HsM. '
          format: date-time
          example: '2021-08-23T16:15:18.123+01:00'
          readOnly: true
        status:
          type: string
          enum:
            - active
            - inactive
            - deleted
          description: The status of the user in terms of his possibilty to interact with the system.
          readOnly: true
      required:
        - emailAddress
    customerRelation:
      title: customerRelation
      type: object
      properties:
        relationId:
          type: string
          format: uuid
          readOnly: true
        parentCustomerId:
          type: string
        childCustomerId:
          type: string
        synchronizationInformation:
          type: string
        lastUpdatedAt:
          type: string
        createdAt:
          type: string
  parameters:
    limit:
      name: limit
      in: query
      required: false
      schema:
        type: integer
        format: int32
        example: 100
        default: 100
        minimum: 10
      description: 'Pagination, page size limit.'
    offset:
      name: offset
      in: query
      required: false
      schema:
        type: integer
        format: int32
        minimum: 0
        example: 200
      description: 'Pagination, offset for returned page.'
    X-Total-Count:
      name: X-Total-Count
      in: header
      required: false
      schema:
        type: integer
        format: int32
      description: Total number of elements in the collection.
    collectionUuid:
      name: uuid
      in: path
      required: true
      schema:
        type: string
        format: uuid
      description: UUID of the collection element
  responses: {}
  examples: {}
